language: java
jdk:
  - openjdk11

script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
jobs:
  include:
    - stage: Test
      script: mvn test -B
    - stage: Generate documentation
      script: mvn javadoc:jar
 
notifications:
  email: mareksoska22@gmail.com
